---
# tasks/main.yml
- name: Include Node.js setup tasks
  ansible.builtin.import_tasks: nodejs.yml
- name: Include Meteor app setup tasks
  ansible.builtin.import_tasks: meteor_app.yml
- name: Include NGINX setup tasks
  ansible.builtin.import_tasks: nginx.yml
- name: Include Cloudflared and hosts setup tasks
  ansible.builtin.import_tasks: cloudflared.yml
