---
# tasks/nodejs.yml
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - wget
      - curl
      - gnupg
      - ca-certificates
      - sudo
    state: present
    update_cache: true

- name: Download Node.js
  ansible.builtin.get_url:
    url: "{{ node_url }}"
    dest: "/tmp/{{ node_dist }}.tar.xz"
    mode: '0644'

- name: Extract Node.js to /opt
  ansible.builtin.unarchive:
    src: "/tmp/{{ node_dist }}.tar.xz"
    dest: /opt
    remote_src: true
    creates: "/opt/{{ node_dist }}"
